### ISSUE TITLE
Ultimate api only returns 48 characters instead of 86

### ISSUE THREAD

**Issue by locl95** [Frannsoft/FrannHammer#304]
I would expect to get all characters from ultimate in the /api/characters?game=ultimate call. Right now I'm only getting 48.

**Comment by Frannsoft** [comment]
Hi!

Thanks for using the api!

It's been a while since I've messed with this code, but I believe this is because there is only data on the Kurogane Hammer website for that amount of characters.

This API pulls data from the Kurogane Hammer website so if the website's page for a character doesn't have any frame data that character in Ultimate, the api won't return data for that character.

**Comment by locl95** [comment]
I see, makes sense then. Tyvm for quick response
